version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: lcatv_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: lcatv_database
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - lcatv_network

  # Backend FastAPI
  backend:
    build:
      context: .
      target: backend
    container_name: lcatv_backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=lcatv_database
      - YOUTUBE_API_KEY=AIzaSyAI1gP7p6rf75Hl4SRzXAUIvqbfWQNt9UI
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app/backend
    networks:
      - lcatv_network
    command: python server.py

  # Frontend Expo/React Native
  frontend:
    build:
      context: .
      target: frontend
    container_name: lcatv_frontend
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - EXPO_PUBLIC_BACKEND_URL=http://localhost:8001
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    networks:
      - lcatv_network
    command: npx expo start --tunnel

volumes:
  mongodb_data:
    driver: local

networks:
  lcatv_network:
    driver: bridge